twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/google_recaptcha_types.html.twig'
    globals:
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        site_url: 'https://forest-butovo.ru'

when@test:
    twig:
        strict_variables: true
